import { useState } from "react";

const formFields = [
    {
        label:
          "If the Publishers Promote you via PPC, will they entitled for Full Commision?",
        showInput: false,
      },
    {
        label:
          "If Publisher Directly Link to your Website from search engine ,will they receive full commission?",
        showInput: false,
      },
    {
        label:
          "If publisher use your Brand name in their Display URL ,will they receive full commission?",
        showInput: false,
      },
  {
    label:
      "If publisher use your Brand name in their paid search title and Discription ,will they receive full commission?",
    showInput: false,
  },
  {
    label:
      "If publisher adds your Brand name into their negetive Keyword list ,will they receive full commission?",
    showInput: false,
  },
  { label: "If publisher Display their adds when your brand name or variations of you brand name are entered as search Keywords ,will they receive full commission?(eg. vodafone ,voda fone) ", showInput: false },
  { label: "If publisher Display their adds when when misspelling of your brand name are entered as keywords ill they receive full commission ?(eg. vodofone) ", showInput: false },
  { label: "If publisher Display their adds when your brand name and another keyword are entered as search keywords ,will they receive full commission ? (e.g vodafone mobile)" , showInput: false },
  { label: "Do you have a restricted Group of publishers who can earn commission on sales generated by brand related terms ? ", showInput: false },
  { label: "For any agreed publisher paid search activity , will publisher be paid for sales generated from the following search engines ?", showInput: false },
  { label: "Google", showInput: true },
  { label: "yahoo", showInput: true },
  { label: "Bing", showInput: true },
  { label: "Other", showInput: true },
  { label: "Are there any specific search terms(keyword) where sales from publisher PPC adds will not be eligible to earn commision", showInput: true },
  { label: "if publishers place shopping ads on a seacrh engine and link directly to your website ,are they eligble to receive full commission ?", showInput: false },
  { label: "if publishers place shopping ads on a seacrh engine such as Comparison Shopping Service(CSS),does this activity needs to be tracked in a seprate specific publisher account ?", showInput: true },

];

export default function LegalTerms() {
  const [formData, setFormData] = useState(
    formFields.reduce((acc, field) => {
      acc[field.label] = { value: "Yes", additionalInfo: "" };
      return acc;
    }, {})
  );

  const handleValueChange = (label, value) => {
    setFormData((prev) => ({
      ...prev,
      [label]: { ...prev[label], value },
    }));
  };

  const handleInfoChange = (label, value) => {
    setFormData((prev) => ({
      ...prev,
      [label]: { ...prev[label], additionalInfo: value },
    }));
  };

  const handleSubmit = () => {
    console.log("Form Data:", formData);
    
    // Add save logic here
  };

  return (
    <div className="p-6 max-w-5xl mx-auto">
      
      <div className="space-y-4">
        {formFields.map(({ label, showInput }) => (
          <div key={label}>
            <div className="border rounded-xl p-4 shadow-sm w-full overflow-x-auto">
              <div className="flex gap-6">
                {/* Field Label */}
                <div className="w-[400px] shrink-0">
                  <p className="text-sm font-medium">{label}</p>
                </div>

                {/* Yes/No Radio Buttons */}
                <div className="flex gap-4 w-[200px] overflow-hidden">
                  <label className="flex items-center gap-2">
                    <input
                      type="radio"
                      name={`${label}-option`}
                      value="Yes"
                      checked={formData[label].value === "Yes"}
                      onChange={() => handleValueChange(label, "Yes")}
                      className="w-4 h-4 text-green-600"
                    />
                    <span className="text-sm">Yes</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input
                      type="radio"
                      name={`${label}-option`}
                      value="No"
                      checked={formData[label].value === "No"}
                      onChange={() => handleValueChange(label, "No")}
                      className="w-4 h-4 text-green-600"
                    />
                    <span className="text-sm">No</span>
                  </label>
                </div>

                {/* Conditional Input */}
                {showInput && (
                  <div className="min-w-[300px]">
                    <input
                      className="w-full border rounded-md p-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      placeholder="Click to edit"
                      value={formData[label].additionalInfo}
                      onChange={(e) =>
                        handleInfoChange(label, e.target.value)
                      }
                    />
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}

        <button
          type="button"
          onClick={handleSubmit}
          className="mt-6 w-full bg-blue-600 text-white py-3 px-4 rounded-lg hover:bg-blue-700 transition-colors font-medium"
        >
          Save
        </button>
      </div>
    </div>
  );
}
