export const userType = {
    id: '', role: "", fullName: '', firstName: '', lastName: '', gender: '', email: '', mobileNo: '', address: '', image: '',
    instagram_username: "",
    instagram_profile_link: "",
    youtube_username: "",
    youtube_profile_link: "",
    twitter_username: "",
    twitter_profile_link: "",
    linkedin_username: "",
    linkedin_profile_link: "",
    website: "",
    description: "",
    tags: [],
    dialCode: '',
    pincode: "",
    social_media_platforms: [],
    category_name: "",
    category_id: "",
    country: "",
    city: "",
    pincode: "",
    affiliate_group: '',
    affiliate_type: '',
    addedBy: null,
}

export let userDetailType={ id:'',fullName: '',firstName:'',lastName:'',gender:'', email: '', mobileNo: '',address:'',image:[],role:'',
    instagram_username: "",
    instagram_profile_link: "",
    youtube_username: "",
    youtube_profile_link: "",
    twitter_username: "",
    twitter_profile_link: "",
    linkedin_username: "",
    linkedin_profile_link: "",
    website:"",
    description:"",
    tags: [],
    dialCode:'+1',
    pincode:"",
    social_media_platforms:[],
    category_name:"",
    category_id:"",
    country:"",
    city:"",
    pincode:"",
    affiliate_group:"",
    address2:"",
    brand_name:"",
    affiliate_group_name:'',
    reffering_affiliate:'',
    parter_manager_name:'',
    account_executive_name:'',
    cellDialCode:'', work_phone :'',
    language:'',
    tax_detail:'',
    default_invoice_setting:'',
    payment_method:'',
    accountholder_name: '',
    routing_number: '',
    account_number: '',
    ssn_number:'',
    company_name: '',
    // dob:''
}

export const affilliateGrouptype={
    id: "",
    group_name: "",
    commision:"",
    group_type:"",
    isDefaultAffiliateGroup:false,
    isArchive:false,
    isPreRegisterLeads:false,
    // status: "",
}
export const CategoryType={id:'',name:'',catType:'',subParentCategory:'',description:'',image:'',order:'',parentCategory:'',status:'active',icon:'',banner:'',altImageName:'',altIconName:'',bannerOverlayHeading:'',bannerOverlayBody:'',description:'',featured:'No',urlKey:'',metaTitle:'',metaDescription:'',keywords:''}
export const roleType={id:'',name:'',status:'active',permissions:{
    //  Done
    readDashboard:false,
    readCustomer:false,
    addCustomer:false,
    editCustomer:false,
    deleteCustomer:false,
    readRole:false,
    addRole:false,
    editRole:false,
    deleteRole:false,
    // Done
    readCategory:false,
    addCategory:false,
    editCategory:false,
    deleteCategory:false,
    readResellerCategory:false,
    addResellerCategory:false,
    editResellerCategory:false,
    deleteResellerCategory:false,
    readAdmins:false,
    addAdmins:false,
    editAdmins:false,
    deleteAdmins:false,
    readTypes:false,
    addTypes:false,
    editTypes:false,
    deleteTypes:false,
    readCategory:false,
    addCategory:false,
    editCategory:false,
    deleteCategory:false,
    readResellerCategory:false,
    addResellerCategory:false,
    editResellerCategory:false,
    deleteResellerCategory:false,
    readPlanFeatures:false,
    addPlanFeatures:false,
    editPlanFeatures:false,
    deletePlanFeatures:false,
    readPlan:false,
    addPlan:false,
    editPlan:false,
    deletePlan:false,
    readCoupons:false,
    addCoupons:false,
    editCoupons:false,
    deleteCoupons:false,
    readCurrency:false,
    addCurrency:false,
    editCurrency:false,
    deleteCurrency:false,
    readBooking:false,
    addBooking:false,
    editBooking:false,
    deleteBooking:false,
    refreshBooking:false,
    readContinents:false,
    addContinents:false,
    editContinents:false,
    deleteContinents:false,
    readCountries:false,
    addCountries:false,
    editCountries:false,
    deleteCountries:false,
    readRegion:false,
    addRegion:false,
    editRegion:false,
    deleteRegion:false,
    readCities:false,
    addCities:false,
    editCities:false,
    deleteCities:false,
    readEmailTemplate:false,
    addEmailTemplate:false,
    editEmailTemplate:false,
    
}}

export const planType={id:'',name:'',price:'',status:'active',interval:'Monthly',category:'',recommended:'',allowedProducts:'',feature:[]}
export const typeType={id:'',name:''}
export const campaignType={
    id: "",
    name: "",
    description: "",
    "category_id": "",
    "sub_category_id": null,
    image: [],
    start_date: "",
    end_date: "",
    opportunity_type: [],
    placement: [],
}

export const addCampaignType = {
    id:'',
    name: "",
    amount: "",
    description: "",
    images: [],
    access_type:'',
    documents: [],
    videos: [],
    affiliate_id: null,
    status: "",
    event_type: [],
}